name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/release.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Release - ${{ matrix.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch: amd64
            strip_cmd: strip
          - target: aarch64-unknown-linux-gnu
            arch: arm64
            strip_cmd: aarch64-linux-gnu-strip
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}
    
    - name: Install cross-compilation tools for ARM64
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Configure cargo for cross-compilation
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        mkdir -p .cargo
        cat >> .cargo/config.toml <<EOF
        [target.aarch64-unknown-linux-gnu]
        linker = "aarch64-linux-gnu-gcc"
        EOF
    
    - name: Build release binary
      run: |
        cargo build --release --locked --target ${{ matrix.target }}
        ${{ matrix.strip_cmd }} target/${{ matrix.target }}/release/xclip
    
    - name: Create tarball
      run: |
        mkdir -p wsl-clip-bridge
        cp target/${{ matrix.target }}/release/xclip wsl-clip-bridge/
        cp -r scripts wsl-clip-bridge/
        cp -r config wsl-clip-bridge/
        cp README.md wsl-clip-bridge/
        tar czf wsl-clip-bridge-linux-${{ matrix.arch }}.tar.gz wsl-clip-bridge
    
    - name: Create checksums
      run: |
        # Copy binary with architecture suffix
        cp target/${{ matrix.target }}/release/xclip xclip-${{ matrix.arch }}
        # Create checksum for tarball
        sha256sum wsl-clip-bridge-linux-${{ matrix.arch }}.tar.gz > wsl-clip-bridge-linux-${{ matrix.arch }}.tar.gz.sha256
        # Create checksum for binary
        sha256sum xclip-${{ matrix.arch }} > xclip-${{ matrix.arch }}.sha256
        # Create combined checksums file
        cat wsl-clip-bridge-linux-${{ matrix.arch }}.tar.gz.sha256 > checksums-${{ matrix.arch }}.txt
        echo "xclip-${{ matrix.arch }}  $(sha256sum xclip-${{ matrix.arch }} | cut -d' ' -f1)" >> checksums-${{ matrix.arch }}.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.arch }}
        path: |
          wsl-clip-bridge-linux-${{ matrix.arch }}.tar.gz
          wsl-clip-bridge-linux-${{ matrix.arch }}.tar.gz.sha256
          checksums-${{ matrix.arch }}.txt
          xclip-${{ matrix.arch }}
          xclip-${{ matrix.arch }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Prepare release files
      run: |
        mkdir -p release
        # Move all artifacts to release directory
        mv artifacts/release-amd64/* release/
        mv artifacts/release-arm64/* release/
        # Combine checksums
        cat release/checksums-*.txt > release/checksums.txt
        rm release/checksums-*.txt
    
    - name: Generate Release Tag
      id: tag
      run: echo "TAG=v$(date +'%Y.%m.%d-%H%M%S')" >> "$GITHUB_OUTPUT"

    - name: Get commit info
      id: commit
      run: |
        echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        echo "MESSAGE=$(git log -1 --pretty=%s)" >> "$GITHUB_OUTPUT"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.TAG }}
        name: Release ${{ steps.tag.outputs.TAG }}
        body: |
          Drop-in xclip replacement for WSL → Perfect for [Claude Code](https://claude.ai/code) screenshot pasting!

          **Latest commit**: `${{ steps.commit.outputs.SHA_SHORT }}` - ${{ steps.commit.outputs.MESSAGE }}

          ## Downloads

          | Architecture | Full Package | Binary Only |
          |--------------|--------------|-------------|
          | **x64/AMD64** (most users) | [wsl-clip-bridge-linux-amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.TAG }}/wsl-clip-bridge-linux-amd64.tar.gz) | [xclip-amd64](https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.TAG }}/xclip-amd64) |
          | **ARM64** | [wsl-clip-bridge-linux-arm64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.TAG }}/wsl-clip-bridge-linux-arm64.tar.gz) | [xclip-arm64](https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.TAG }}/xclip-arm64) |

          📦 **[Installation Instructions](https://github.com/${{ github.repository }}#-quick-start)** • 📖 **[Full Documentation](https://github.com/${{ github.repository }}#readme)** • ✅ **[Verify with checksums.txt](https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.TAG }}/checksums.txt)**
        files: |
          release/wsl-clip-bridge-linux-amd64.tar.gz
          release/wsl-clip-bridge-linux-amd64.tar.gz.sha256
          release/wsl-clip-bridge-linux-arm64.tar.gz
          release/wsl-clip-bridge-linux-arm64.tar.gz.sha256
          release/xclip-amd64
          release/xclip-amd64.sha256
          release/xclip-arm64
          release/xclip-arm64.sha256
          release/checksums.txt
        draft: false
        prerelease: false